### ISSUE TITLE
Bit-widths in (some?) operations must be compared

### ISSUE THREAD

**Issue by pdarragh** [cmsc430/a86#3]
A student attempted to compile this code:

```scheme
;; 2^32 - 16
(seq
  (Mov 'rdx 4294967280)
  (And 'eax 'rdx))
```

and they got this error:

```text
assembly error: make sure to use `prog` to construct an assembly program
if you did and still get this error; please share with course staff.

/var/tmp/nasm17077944821707794482656.s:8: error: invalid combination of opcode and operands
```

Apparently, [the specification of `and`](https://www.felixcloutier.com/x86/and) cares about the order of the operands: if the left operand is only 32 bits wide (e.g., `eax`), then the second operand can only be 32 bits wide. However, if the first operand is 64 bits wide (e.g., `rax`), then the second operand can be of any lesser width (e.g., `eax`) and that second operand will be sign-extended.

So we'll want to update the checks in the a86 instructions to look for this, and then update the course notes accordingly. I assume `and` is not the only instruction featuring this behavior, so we'll have to look through the others to see what else ought to be changed.

**Comment by dvanhorn** [comment]
I think the right move is to support all of the registers and check these things.  But... `and rax, edx` doesn't assemble in nasm.

One thing we will also need to do is check immediate arguments based on the size of the register, e.g. `(And 'eax n)` needs to check that `n` fits in 32 bits.  Currently, we just check that immediates fit in 64 bits.

**Comment by dvanhorn** [comment]
I believe this issue has been addressed now.  The example results in a construction-time error:
```racket
> (require a86)
> (seq (Mov 'rdx 4294967280)
       (And 'eax 'rdx))
And: cannot move between registers of unequal size; given 'eax (32-bit), 'rdx (64-bit)
```
