### ISSUE TITLE
Prevent arbitrary x86 insertion

### ISSUE THREAD

**Issue by pdarragh** [cmsc430/a86#5]
The implementation of comment rendering in the printer (below) allows the insertion of arbitrary x86 instructions, which we don't want. I think this can be fixed by replacing the existing implementation with one that replaces newlines `\n` with commented newlines `\n;;` (or something prettier).

https://github.com/cmsc430/www/blob/82864f846a7f8f6645821e237de42fac94dff157/langs/a86/printer.rkt#L241-L245

**Comment by dvanhorn** [comment]
Seems like you could also just disallow newlines in the comment constructors.  That is the only escape hatch AFAICT.
